version: 0.2

phases:
  install:
    on-failure: CONTINUE
    commands:
      - ls
      - aws --version
      - cat file.yaml
      - aws cloudformation update-stack --stack-name web-app --template-url https://github.com/ligh1yagami/cloudformation-project/blob/main/file.yaml


