version: 0.2

phases:
  install:
    on-failure: CONTINUE
    commands:
      - ls
      - aws --version
      - aws cloudformation update-stack --stack-name web-app --template-url https://ligh1s-github-actions.s3.ap-south-1.amazonaws.com/file.yaml
